services:
  app:
    image: mintall-nft-cert-api
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network
    container_name: mintall-nft-cert-api
    environment:
      - PORT=3000
      - NODE_ENV=vault
      - VAULT_TOKEN_FILE=/etc/vault/token
      - VAULT_ADDR=http://vault:8200
      - DATABASE_SECRET_NAME=kv/data/DATABASE_INFO/POSTGRES/DB1
      - REDIS_SECRET_NAME=kv/data/REDIS_INFO/DB1
      - SERVICE_SECRET_NAME=kv/data/MINTALL_SERVICE_INFO
    working_dir: /app
    volumes:
      # - $HOME/.aws:/root/.aws
      - vault-token:/etc/vault
    ports:
      - '4000:3000'
    depends_on:
      - vault-agent
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M

  vault-agent:
    image: hashicorp/vault:1.19
    container_name: mintall-nft-cert-api-vault-agent
    networks:
      - app-network
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault/vault-agent.hcl:/etc/vault/vault-agent.hcl:ro
      - ./vault/role-id:/etc/vault/role-id:ro
      - ./vault/secret-id:/etc/vault/secret-id:ro
      - vault-token:/etc/vault
      - type: tmpfs
        target: /vault/logs
        tmpfs:
          size: 100M
      - type: tmpfs
        target: /vault/file
        tmpfs:
          size: 100M
    command: vault agent -config=/etc/vault/vault-agent.hcl
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 256M
        reservations:
          cpus: '0.05'
          memory: 64M

networks:
  app-network:
    external: true

volumes:
  vault-token:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
